name: '${projectName}'
version: '${projectVersion}'
main: '${projectMainClass}'
api-version: 1.19
authors: [ CKATEPTb ]
description: Use SQLite, MySQL and even MongoDB inside Spigot in Entity <=> Repository mode.